// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseProgramPath() {
  return window['go']['main']['App']['ChooseProgramPath']();
}

export function ChooseProgramTarget() {
  return window['go']['main']['App']['ChooseProgramTarget']();
}

export function ChooseWorkingDirectory() {
  return window['go']['main']['App']['ChooseWorkingDirectory']();
}

export function ClearProgramLogs(arg1) {
  return window['go']['main']['App']['ClearProgramLogs'](arg1);
}

export function CreateProgram(arg1) {
  return window['go']['main']['App']['CreateProgram'](arg1);
}

export function DeleteProgram(arg1) {
  return window['go']['main']['App']['DeleteProgram'](arg1);
}

export function GetProgram(arg1) {
  return window['go']['main']['App']['GetProgram'](arg1);
}

export function GetProgramLogs(arg1, arg2) {
  return window['go']['main']['App']['GetProgramLogs'](arg1, arg2);
}

export function ListPrograms(arg1) {
  return window['go']['main']['App']['ListPrograms'](arg1);
}

export function ReconnectPrograms() {
  return window['go']['main']['App']['ReconnectPrograms']();
}

export function StartProgram(arg1) {
  return window['go']['main']['App']['StartProgram'](arg1);
}

export function StopProgram(arg1) {
  return window['go']['main']['App']['StopProgram'](arg1);
}

export function UpdateProgram(arg1, arg2) {
  return window['go']['main']['App']['UpdateProgram'](arg1, arg2);
}
