// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {programs} from '../models';

export function ChooseProgramPath():Promise<string>;

export function ChooseProgramTarget():Promise<string>;

export function ChooseWorkingDirectory():Promise<string>;

export function ClearProgramLogs(arg1:string):Promise<void>;

export function CreateProgram(arg1:programs.Input):Promise<programs.View>;

export function DeleteProgram(arg1:string):Promise<void>;

export function GetProgram(arg1:string):Promise<programs.View>;

export function GetProgramLogs(arg1:string,arg2:programs.LogQuery):Promise<programs.LogView>;

export function ListPrograms(arg1:programs.ListQuery):Promise<Array<programs.View>>;

export function ReconnectPrograms():Promise<void>;

export function StartProgram(arg1:string):Promise<void>;

export function StopProgram(arg1:string):Promise<void>;

export function UpdateProgram(arg1:string,arg2:programs.Input):Promise<programs.View>;
